apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1) Pull the shared resources from base so there is something to build
resources:
  - ../../base

# 2) Add production-wide labels (modern field replaces commonLabels)
labels:
  - pairs:
      env: production

# 3) Prefix all resource names in production
namePrefix: prod-
