apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

configMapGenerator:
  - name: my-configmap
    literals:
      - key1=value1
      - key2=value2

secretGenerator:
  - name: my-secret
    literals:
      - username=admin
      - password=s3cr3t
