name: Deploy with Kustomize

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sanity: who am I and which clusters exist?
        run: |
          set -e
          echo "AWS CLI version:"
          aws --version
          echo "Caller identity:"
          aws sts get-caller-identity
          echo "Clusters in region ${AWS_REGION}:"
          aws eks list-clusters --region "${AWS_REGION}"
          echo "Describe cluster ${ { secrets.EKS_CLUSTER_NAME } }"
          aws eks describe-cluster --region "${AWS_REGION}" --name "${{ secrets.EKS_CLUSTER_NAME }}" --query "cluster.{name:name,endpoint:endpoint}" --output json

      - name: Update kubeconfig for EKS
        run: |
          set -e
          aws eks update-kubeconfig --region "${AWS_REGION}" --name "${{ secrets.EKS_CLUSTER_NAME }}"

      - name: Kubectl sanity
        run: |
          kubectl version --client
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k ./overlays/production/
